user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 10m;

    server {
        listen 80;
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/certs/certificate.crt;
        ssl_certificate_key /etc/nginx/certs/private_key.key;

        keepalive_timeout 70;

        # Cabeceras necesarias para Django/Wagtail detrás de proxy
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        location / {
            proxy_pass http://django:8000;
        }

        location /assets/js/ {
            proxy_pass http://vite:3000;
        }
    }
}
